### ISSUE TITLE
elaborating typechecker for LF?

### ISSUE THREAD

**Issue by jonsterling** [jonsterling/racket-grit#6]
Right now, you have to write LF terms in a very bureaucratic way, being careful to put in nullary `pi` types where it is required by the grammar, nullary lambda abstractions, and variables must be applied to (possibly) nullary spines, everything must be eta-long, etc. This is all extremely nice for writing programs that consume LF terms, since it is completely canonical, but it is not so nice for writing programs that construct LF terms.

It is possible to elaborate a more naïve syntax to the correct form in a type-directed way, so one option would be to replace the typechecker with an elaborator. The elaborator would insert nullary pis and lambda where necessary, and ensure that variables are fully eta-expanded in the appropriate way / in accordance with their types.

This is not strictly necessary for now, but it could be important in the future. My suggestion is that we consider doing this, but not worry about it until we have a concrete case in mind where we really want it.

**Comment by david-christiansen** [comment]
I think we can close this one. We figured out at OPLSS that what we really wanted was syntactic coercions, and that seems to work now. Right?
